Vagrant.configure("2") do |config|

  config.vm.define "redirector" do |config|
    VM_NAME= "redirector"
    config.vm.box = "bento/ubuntu-21.04"
    config.vm.box_check_update = false
    config.vm.hostname = "#{VM_NAME}"
    config.vm.boot_timeout = 600
    config.vm.network :public_network, ip: "192.168.0.5", bridge: "tap0"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "#{VM_NAME}"

      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

    end
  end
end
