---


- name: Reload Apache
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: reload systemctl
  command: systemctl daemon-reload