Vagrant.configure("2") do |config|
  config.vm.define "nashua" do |config|
    VM_NAME_WIN= "nashua"
    config.vm.box = "d1vious/windows10"
    config.vm.box_check_update = false
    config.vm.hostname = "#{VM_NAME_WIN}"
    config.vm.boot_timeout = 600
    config.vm.communicator = "winrm"
    config.winrm.basic_auth_only = true
    config.winrm.timeout = 300
    config.winrm.retry_limit = 20
    config.vm.network "forwarded_port", guest: 5985, host: 6016
    config.vm.network :public_network, ip: "10.0.1.6", bridge: "tap0"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  
    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          ansible_port: 6016,
          ansible_winrm_scheme: 'http',
          splunk_server: "0",
          splunk_indexer_ip: "10.0.1.12",
          caldera_server_ip: '10.0.1.12',
          win_password: 'I-l1ke-Attack-Range!',
          splunk_uf_win_url: 'https://download.splunk.com/products/universalforwarder/releases/8.0.2/windows/splunkforwarder-8.0.2-a7f645ddaf91-x64-release.msi',
          nxlog_url: '',
          install_dsp: '',
          win_sysmon_url: 'https://attack-range-appbinaries.s3-us-west-2.amazonaws.com/Sysmon.zip',
          win_sysmon_template: 'AttackRangeSysmon.xml',
          splunk_admin_password: 'I-l1ke-Attack-Range!',
          windows_server_join_domain: '1',
          windows_domain_controller_private_ip: '10.0.0.4',
          run_demo: '',
          demo_scenario: '',
          capture_attack_data: '',
          win_timezone: 'GMT Standard Time'
        }
        ansible.playbook = "../../ansible/windows_workstation.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
    end
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME_WIN}"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
  
end
  