Vagrant.configure("2") do |config|
  config.vm.define "team-server" do |config|
    VM_NAME_KALI= "team-server"
    config.vm.box = "kalilinux/rolling"
    config.vm.box_check_update = false
    config.vm.boot_timeout = 600
    config.vm.hostname = "#{VM_NAME_KALI}"
    config.vm.network :public_network, ip: "192.168.0.4", bridge: "tap0"
    config.vm.network "forwarded_port", guest: 3389, host: 13389
    # config.vm.synced_folder "./synced_folder", "/vagrant_data"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/kali_linux.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_python_interpreter: "/usr/bin/python3",
          run_demo: '',
          demo_scenario: ''
        }
    end

    config.vm.provision "shell" do |cmd|
      cmd.path = "./provision-kali.sh"
    end

    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME_KALI}"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end

end