---

- name: copy commands.rc to kali linux
  copy:
    src: commands.rc
    dest: /var/www/commands.rc

- name: copy meterpreter.rc to kali linux
  copy:
    src: meterpreter.rc
    dest: /var/www/meterpreter.rc

- name: copy meterpreter.rc to kali linux
  copy:
    src: meterpreter.rc
    dest: /var/www/meterpreter.rc

- name: copy PsExec64.exe to kali linux
  copy:
    src: PsExec64.exe
    dest: /var/www/PsExec64.exe

- name: copy run_metasploit.py to kali linux
  copy:
    src: run_metasploit.py
    dest: /var/www/run_metasploit.py

- name: Make run_metasploit.py executable
  command: chmod +x /var/www/run_metasploit.py

- name: copy attack.service to kali linux
  copy:
    src: attack.service
    dest: /etc/systemd/system/attack.service
    mode: '0644'
  become: yes

- name: setup metasploit database
  command: service postgresql start
  become: yes

- name: setup metasploit service
  command: msfdb init
  become: yes

- name: reload systemctl
  command: systemctl daemon-reload
  become: yes

- name: enable attack
  command: systemctl enable attack.service
  become: yes

- name: enable attack
  command: systemctl start attack.service
  become: yes
