---

- name: Download Splunk puttyX.exe from S3 bucket
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"
    (New-Object System.Net.WebClient).DownloadFile("https://attack-range-appbinaries.s3-us-west-2.amazonaws.com/puttyX.exe", "C:\puttyX.exe")

# - name: copy malicious putty
#   win_copy:
#     src: puttyX.exe
#     dest: C:\puttyX.exe

- name: Create new SMB share
  win_shell: New-SmbShare -Name evil -Path C:\ -FullAccess attackrange\Administrator
