---

# Install latest Atomic Red Team from github

- name: Create .local directory 
  file:
    path: "{{repo_local}}"
    state: directory

- name: Download & extract Atomic Red Team
  ansible.builtin.unarchive:
    src: "{{ atomic_git_link }}"
    dest: "{{repo_local}}"
    remote_src: yes
    
- name: Wait for extraction
  wait_for:
    path: "{{repo_local}}/atomic-red-team-master/atomics"
    state: present
    msg: Timeout to waiting for path {{repo_local}}/atomic-red-team-master/atomics

# Create a local repo of all ART resource which the atomics will use during execution of a technique
# Normally, these resources are pulled from the internet during execution.
# Since we don't have internet access, we need to redirect calls to the internet into this local repo
- name: Create URL list of Atomic Red Team resource
  shell: "grep -Eoh 'https://[a-zA-Z0-9./?=_%:-]*' */*.yaml | sort -u | sed 's/[^[:alnum:]]$//' "
  args:
    chdir: "{{repo_local}}/atomic-red-team-master/atomics"
  register: grep_output
  ignore_errors: true

- debug:
    var: grep_output.stdout_lines[-10:]
  when: grep_output.stdout != ""

- name: Create directories 
  file: path={{ document_root }}/{{ (item.split('://')[1]).split('/')[:-1] | join('/') }} state=directory
  with_items: 
    - "{{ grep_output.stdout_lines | list }}"
    - "{{ atomic_git_link }}"
  when: item.split('://')[1] is defined

### Stage ART resources (1 of 2) - URLs from Atomics
- name: Scrape URLs from Atomics
  get_url:
    url: "{{ item }}"
    dest: "{{ document_root }}/{{ item.split('://')[1] }}"
  with_items: "{{ grep_output.stdout_lines | list }}"
  when: item.split('://')[1] is defined
  ignore_errors: true

- name: Find atomics yaml files
  shell: "find $(pwd) -name '*.yaml'"
  args:
    chdir: "{{repo_local}}/atomic-red-team-master/atomics"
  register: find_output

- debug:
    var: find_output.stdout_lines[-5:]
  when: find_output.stdout != ""

- name: Make atomics point their web requests to our S3 bucket
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: 'https://'
    replace: 'http://10.0.2.2/sar/www/'
  with_items: "{{ find_output.stdout_lines }}"

- name: Zip modified ART repo and replace 
  community.general.archive: 
    path: "{{repo_local}}/atomic-red-team-master"
    dest: "{{ document_root }}/{{ atomic_git_link.split('://')[1] }}"
    format: zip

### MANUAL step! ###
### Copy internet:/var/www/* to S3
# On dev box: $ vagrant scp internet:/var/www ~/www
# On dev box: Upload ~/www to S3 bucket via browser

### MANUAL step! ###
### Copy engenuity/ansible to S3
# On dev box: Upload engenuity/ansible to S3 bucket via browser



### Stage ART resources (2 of 2) - Invoke Atomic Raw resources

- name: Download & extract Invoke Atomic Red Team
  ansible.builtin.unarchive:
    src: "{{ invoke_atomic_git_link }}"
    dest: "{{repo_local}}"
    remote_src: yes
    
- name: Wait for extraction
  wait_for:
    path: "{{repo_local}}/invoke-atomicredteam-master"
    state: present
    msg: Timeout to waiting for path {{repo_local}}/invoke-atomicredteam-master

- name: Find atomics ps1 files
  shell: "find $(pwd) -name '*.ps1'"
  args:
    chdir: "{{repo_local}}/invoke-atomicredteam-master"
  register: find_output

- debug:
    var: find_output.stdout_lines[-5:]
  when: find_output.stdout != ""

- name: Make web links point to our S3 bucket
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: 'https://'
    replace: 'http://10.0.2.2/sar/www/'
  with_items: "{{ find_output.stdout_lines }}"


- name: Create invoke ART directories
  file: path={{ item }} state=directory
  with_items: 
    - "{{ document_root }}/{{ (invoke_atomic_git_link.split('://')[1]).split('/')[:-1] | join('/') }}"
    - "{{ invoke_atomic_raw_path }}"

- name: Move modified Invoke ART repo to www 
  shell: cp -rf {{repo_local}}/invoke-atomicredteam-master/* {{invoke_atomic_raw_path}}/master

- name: Create modified Invoke ART archive and replace 
  community.general.archive: 
    path: "{{repo_local}}/invoke-atomicredteam-master"
    dest: "{{ document_root }}/{{ invoke_atomic_git_link.split('://')[1] }}"
    format: zip
  register: archive_output

- debug:
    var: archive_output