---

- name: Install Packages
  apt: 
    pkg: 
      - python3-pip
      - unzip
    cache_valid_time: 86400 # Run apt update if it has been over 1 day since last update
 
# - include: install_apache.yml
- include: install_atomic.yml
# - include: install_dnschef.yml



