---

# - name: copy commands.rc to kali linux
#   copy:
#     src: commands.rc
#     dest: /var/www/commands.rc


# - name: copy attack.service to kali linux
#   copy:
#     src: attack.service
#     dest: /etc/systemd/system/attack.service
#     mode: '0644'
#   become: yes

- name: install pip
  apt: 
    pkg: python3-pip

- name: Download & extract Atomic Red Team
  ansible.builtin.unarchive:
    src: https://github.com/redcanaryco/atomic-red-team/archive/refs/heads/master.zip"
    dest:  ~/.local
    remote_src: yes

- name: Create URL list of Atomic Red Team resources
  shell: "grep -Eo '(http|https)://[^/"]+' | sort -u"
  args:
    chdir: " ~/.local/atomic-red-team-master/atomics"
  register: grep_output
  ignore_errors: true

- debug:
    var: grep_output.stdout_lines
  when: grep_output.stdout != "