Vagrant.configure("2") do |config|
  config.vm.define "dc" do |config|
    VM_NAME_WIN_DC= "dc"
    # config.vm.hostname = "#{VM_NAME_WIN_DC}"
    # config.vm.box = "d1vious/windows2016"
    config.vm.box = "zt-dc"
    config.vm.box_check_update = false    
    config.vm.boot_timeout = 600
    config.vm.communicator = "winrm"
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true
    config.winrm.timeout = 300
    config.winrm.retry_limit = 20
    config.vm.network "forwarded_port", guest: 5985, host: 6004
    config.vm.network :public_network, ip: "192.168.1.30", bridge: "tap0"

    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          ansible_port: 6004,
          ansible_winrm_scheme: 'http',
          # splunk_server: "1",
          splunk_indexer_ip: "192.168.1.20",
          win_password: 'I-l1ke-Attack-Range!',
          splunk_uf_win_url: 'https://download.splunk.com/products/universalforwarder/releases/8.0.2/windows/splunkforwarder-8.0.2-a7f645ddaf91-x64-release.msi',
          nxlog_url: '',
          install_dsp: '',
          win_sysmon_url: 'https://attack-range-appbinaries.s3-us-west-2.amazonaws.com/Sysmon.zip',
          win_sysmon_template: 'AttackRangeSysmon.xml',
          splunk_admin_password: 'I-l1ke-Attack-Range!',
          capture_attack_data: '',
          win_timezone: 'GMT Standard Time',
        }
        ansible.playbook = "../../ansible/windows_dc.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
    end

    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME_WIN_DC}"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      # Disable some virtualization options that are causing issues in VirtualBox
      # vb.customize ["modifyvm", :id, "--pae", "off"] # Physical Address Extension - only needed for 32-bit guest OS
      # vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

end