Vagrant.configure("2") do |config|
  config.vm.define "internet" do |config|
    VM_NAME= "internet"
    VM_IP= "192.168.0.5"
    config.vm.box = "bento/ubuntu-21.04"
    config.vm.box_check_update = false
    config.vm.boot_timeout = 600
    config.vm.hostname = "#{VM_NAME}"
    config.vm.network "public_network", ip: "#{VM_IP}", bridge: "tap0"
    config.vm.network "forwarded_port", guest: 22, host: 2222

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/internet.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          vm_ip: "#{VM_IP}"
        }
    end


    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = false
      vb.name = "#{VM_NAME}"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]      
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

end