- name: Firewall rule to allow pings
  community.windows.win_firewall_rule:
    name: ICMP Allow incoming V4 echo request
    enabled: yes
    state: present
    profiles: domain,private,public
    action: allow
    direction: in
    protocol: icmpv4
    icmp_type_code: '8:*'